<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <TieredPGO>true</TieredPGO>
    <EnableDynamicPGO>true</EnableDynamicPGO>
    <Optimize>true</Optimize>
    <InvariantGlobalization>true</InvariantGlobalization>
    <RootNamespace>Zoomies</RootNamespace>
    <AssemblyName>zoomies</AssemblyName>
    <Version>4.55</Version>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Stats)' == 'true'">
    <DefineConstants>$(DefineConstants);STATS</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\nnue\best.nnue" Condition="Exists('..\nnue\best.nnue')" LogicalName="best.nnue" />
  </ItemGroup>

</Project>
